spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gymtopia
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mjjy1081604@
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true