### 회원 정보 가져오기
GET http://localhost:8080/member/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmY3quLjrj5kiLCJyb2xlIjoiTUVNQkVSIiwiZW1haWwiOiJnaWxkb25nQG5hdmVyLmNvbSIsImlhdCI6MTcwNjI4MzIzMywiZXhwIjoxNzA2Mjg2ODMzfQ.3Or68llZNT2Buc7eIFOCsfqFkscakp6I4Cwr8oPChE9rdeTOk8PdPuj3vWeGof6STjblwUDIhUUd5b7y6u6gkA

### 회원 정보 수정
PUT http://localhost:8080/member/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmY3quLjrj5kiLCJyb2xlIjoiTUVNQkVSIiwiZW1haWwiOiJnaWxkb25nQG5hdmVyLmNvbSIsImlhdCI6MTcwNjI4MzIzMywiZXhwIjoxNzA2Mjg2ODMzfQ.3Or68llZNT2Buc7eIFOCsfqFkscakp6I4Cwr8oPChE9rdeTOk8PdPuj3vWeGof6STjblwUDIhUUd5b7y6u6gkA

{
  "number": "010-3333-4444",
  "address": "제주시 어쩌구 저쩌구",
  "birth": "2020-04-25",
  "password": "54321"
}

### 트레이너 정보 가져오기
GET http://localhost:8080/trainer/info
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmY3quLjrj5kiLCJyb2xlIjoiVFJBSU5FUiIsImVtYWlsIjoiZ2lsZG9uZ0BuYXZlci5jb20iLCJpYXQiOjE3MDYyODMxODMsImV4cCI6MTcwNjI4Njc4M30.leVFtcUybytEz0jIVEMvJAsybxWwPk_y_bIaQRouDlVJwH4atp7o2emikTWlvjN0FmVyR9dMoPK_2D4n8kgo6g

### 회트레이너원 정보 수정
PUT http://localhost:8080/trainer/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmY3quLjrj5kiLCJyb2xlIjoiVFJBSU5FUiIsImVtYWlsIjoiZ2lsZG9uZ0BuYXZlci5jb20iLCJpYXQiOjE3MDYyODMxODMsImV4cCI6MTcwNjI4Njc4M30.leVFtcUybytEz0jIVEMvJAsybxWwPk_y_bIaQRouDlVJwH4atp7o2emikTWlvjN0FmVyR9dMoPK_2D4n8kgo6g

{
  "number": "010-3333-4444",
  "birth": "2020-04-25",
  "password": "54321",
  "gymName": "길동Gym",
  "introduction": "안녕하세요 길동Gym 입니다. 반갑습니다.",
  "career": "2022 파이널 챔피언 우승, 2023 월드챔피언십 준우승, 등등"

}