### 원하는 트레이너에게 운동 신청
POST http://localhost:8080/member/register/trainer/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA3MDk3NTkzLCJleHAiOjE3MDcxMDExOTN9.7ULZ819xPYY9qQCRd8ygYK-AHRv-FU3uJoTEW_lhQxps5zlzzU9AwXSQbDL5qTbhpOwoBER37u1nPV4E5s9nwg
Content-Type: application/json

{
  "startDate": "2024-01-10",
  "endDate": "2024-03-20"
}