###  회원 -> 트레이너 리뷰
POST http://localhost:8080/member/review/trainer/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA3MTAyMzgxLCJleHAiOjE3MDcxMDU5ODF9.QYnnR2cYViTfQ-i03i9n0NP_rPaNOI0FXFxQdrguplb22NlGOE_6y50RLDOZcIRpXWLIDsBcvefOF5-BXOn34Q
Content-Type: application/json

{
  "contents": "트레이너에 대한 리뷰1"
}

### 회원 -> 트레이너 리뷰 수정
PUT http://localhost:8080/member/review/1/trainer/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA3MTAyMzgxLCJleHAiOjE3MDcxMDU5ODF9.QYnnR2cYViTfQ-i03i9n0NP_rPaNOI0FXFxQdrguplb22NlGOE_6y50RLDOZcIRpXWLIDsBcvefOF5-BXOn34Q
Content-Type: application/json

{
  "contents": "트레이너에 대한 수정된 리뷰"
}

### 회원 -> 트레이너 리뷰 삭제
DELETE http://localhost:8080/member/review/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA3MTAyMzgxLCJleHAiOjE3MDcxMDU5ODF9.QYnnR2cYViTfQ-i03i9n0NP_rPaNOI0FXFxQdrguplb22NlGOE_6y50RLDOZcIRpXWLIDsBcvefOF5-BXOn34Q

### 트레이너에게 작성된 리뷰 확인
GET http://localhost:8080/trainer/review?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtirjroIjsnbTrhIgzIiwicm9sZSI6IlRSQUlORVIiLCJlbWFpbCI6IlRyYWluZXIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNzEwMjEyNywiZXhwIjoxNzA3MTA1NzI3fQ.3KNC8LMv9_L4rN-NFtrPotCvn78eUPQshSVTKBXiq5ORzg4B-hUQmUhm9BqavRn_z9RMYSVH0rx_uXBwDMNj6Q

### 트레이너에게 작성된 리뷰 삭제
DELETE http://localhost:8080/trainer/review/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtirjroIjsnbTrhIgzIiwicm9sZSI6IlRSQUlORVIiLCJlbWFpbCI6IlRyYWluZXIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNzEwMjEyNywiZXhwIjoxNzA3MTA1NzI3fQ.3KNC8LMv9_L4rN-NFtrPotCvn78eUPQshSVTKBXiq5ORzg4B-hUQmUhm9BqavRn_z9RMYSVH0rx_uXBwDMNj6Q

