### 이미지 저장
POST http://localhost:8080/member/journal/upload

###
DELETE http://localhost:8080/member/journal/delete/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA2NTM0MTA4LCJleHAiOjE3MDY1Mzc3MDh9.02B1iUweXmyc_eFFohIX5ypatz-yGWRaCEMgHuJhxfqjI4Z3sMw0EeprneKCdQxFfm-4vrXndSEa_vZ95Y-Ukg

###
DELETE http://localhost:8080/member/journal/delete/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA2NTM0MTA4LCJleHAiOjE3MDY1Mzc3MDh9.02B1iUweXmyc_eFFohIX5ypatz-yGWRaCEMgHuJhxfqjI4Z3sMw0EeprneKCdQxFfm-4vrXndSEa_vZ95Y-Ukg

###
DELETE http://localhost:8080/member/journal/delete/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA2NTM0MTA4LCJleHAiOjE3MDY1Mzc3MDh9.02B1iUweXmyc_eFFohIX5ypatz-yGWRaCEMgHuJhxfqjI4Z3sMw0EeprneKCdQxFfm-4vrXndSEa_vZ95Y-Ukg

###
DELETE http://localhost:8080/member/journal/delete/7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIAxIiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDFAbmF2ZXIuY29tIiwiaWF0IjoxNzA2NTM0MTA4LCJleHAiOjE3MDY1Mzc3MDh9.02B1iUweXmyc_eFFohIX5ypatz-yGWRaCEMgHuJhxfqjI4Z3sMw0EeprneKCdQxFfm-4vrXndSEa_vZ95Y-Ukg