### 트레이너 특별 프로그램 등록
POST http://localhost:8080/trainer/program
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtirjroIjsnbTrhIgzIiwicm9sZSI6IlRSQUlORVIiLCJlbWFpbCI6IlRyYWluZXIzQG5hdmVyLmNvbSIsImlkIjo1LCJpYXQiOjE3MDc3NTEyMjcsImV4cCI6MTcwNzc1NDgyN30.ZOa_O0bkwD_ouaWa0gK-DdWEh94lhlHxMIGwXuNcyej9HNPSs4z4aLHM93y1aqimWbSOFJzqsuWsEOhyqKu-Mw

{
  "programName": "Test Program",
  "deadlineDate": "2024-02-20",
  "recruitCount": 10
}

### 트레이너 특별프로그램 마감
PUT http://localhost:8080/trainer/program/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtirjroIjsnbTrhIgzIiwicm9sZSI6IlRSQUlORVIiLCJlbWFpbCI6IlRyYWluZXIzQG5hdmVyLmNvbSIsImlkIjo1LCJpYXQiOjE3MDc3NTEyMjcsImV4cCI6MTcwNzc1NDgyN30.ZOa_O0bkwD_ouaWa0gK-DdWEh94lhlHxMIGwXuNcyej9HNPSs4z4aLHM93y1aqimWbSOFJzqsuWsEOhyqKu-Mw

### 회원 특별 프로그램 조회
GET http://localhost:8080/member/program
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIA5Iiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDlAbmF2ZXIuY29tIiwiaWQiOjEwLCJpYXQiOjE3MDc3NTE0NjMsImV4cCI6MTcwNzc1NTA2M30.LnnyL05vlKDWIhiusvqwi6Qu3Y2PoaQLKPdUA1vuvTGPoQkdoOAliXfjASnqTG1rCOcjX1KNopIa2pwt2p7Nrg

### 회원 특별 프로그램 신청
POST http://localhost:8080/member/program/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLsnKDsoIA5Iiwicm9sZSI6Ik1FTUJFUiIsImVtYWlsIjoidGVzdDlAbmF2ZXIuY29tIiwiaWQiOjEwLCJpYXQiOjE3MDc3NTE0NjMsImV4cCI6MTcwNzc1NTA2M30.LnnyL05vlKDWIhiusvqwi6Qu3Y2PoaQLKPdUA1vuvTGPoQkdoOAliXfjASnqTG1rCOcjX1KNopIa2pwt2p7Nrg
